name: CodeSpell Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - develop

jobs:
  codespell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CodeSpell
        run: pip install codespell

      - name: Run CodeSpell
        run: |
          codespell --config ./style/codespell/setup.cfg
